name: quiz_app
title: WowQuiz
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Build version information
version: 1.0.0+1

# Environment and SDK constraints
environment:
  sdk: ">=3.1.0 <4.0.0"

# Flutter and Dart dependencies
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  shared_preferences: ^2.2.1
  url_launcher: ^6.0.0
  cupertino_icons: ^1.0.2

# Development dependencies (for testing)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

# Assets configuration
assets:
  - assets/images # You can specify individual asset files here if needed
  # Example of specifying assets in a directory:
  # An image asset can refer to one or more resolution-specific "variants."
  # For details regarding adding assets from package dependencies, see the provided links.

# Font configuration (example provided but commented out)
# fonts:
#   - family: Roboto
#     fonts:
#       - asset: fonts/Roboto-Regular.ttf
#       - asset: fonts/Roboto-Bold.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies, see the provided link.
